// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// HellosColumns holds the columns for the "hellos" table.
	HellosColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString, Default: ""},
		{Name: "body", Type: field.TypeString, Default: ""},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "slug", Type: field.TypeString, Unique: true},
		{Name: "user_id", Type: field.TypeInt, Nullable: true},
	}
	// HellosTable holds the schema information for the "hellos" table.
	HellosTable = &schema.Table{
		Name:       "hellos",
		Columns:    HellosColumns,
		PrimaryKey: []*schema.Column{HellosColumns[0]},
	}
	// YmirsColumns holds the columns for the "ymirs" table.
	YmirsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "version", Type: field.TypeString, Default: "alpha-test-dev1"},
	}
	// YmirsTable holds the schema information for the "ymirs" table.
	YmirsTable = &schema.Table{
		Name:       "ymirs",
		Columns:    YmirsColumns,
		PrimaryKey: []*schema.Column{YmirsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		HellosTable,
		YmirsTable,
	}
)

func init() {
}
