// Package adapters are the glue between components and external sources.
// # This manifest was generated by ymir. DO NOT EDIT.
package adapters

import (
	"database/sql"
	"database/sql/driver"
	"fmt"

	"entgo.io/ent/dialect"
	sqlEnt "entgo.io/ent/dialect/sql"
	"github.com/rs/zerolog/log"
	"modernc.org/sqlite"
)

type sqlite3Driver struct {
	*sqlite.Driver
}

type sqlite3DriverConn interface {
	Exec(string, []driver.Value) (driver.Result, error)
}

// Open is wrapper open the connection of sqlite driver.
func (d sqlite3Driver) Open(name string) (conn driver.Conn, err error) {
	conn, err = d.Driver.Open(name)
	if err != nil {
		return
	}
	_, err = conn.(sqlite3DriverConn).Exec("PRAGMA foreign_keys = ON;", nil)
	if err != nil {
		err = conn.Close()
	}
	return
}

func init() {
	sql.Register("sqlite3", sqlite3Driver{Driver: &sqlite.Driver{}})
}

var HelloSQLiteOpen = sqlEnt.Open // HelloSQLiteOpen will invoke to test case.

// HelloSQLite is data of instances.
type HelloSQLite struct {
	File   string `json:"file"`
	driver *sqlEnt.Driver
}

// Open is open the connection of sqlite.
func (h *HelloSQLite) Open() (*sqlEnt.Driver, error) {
	if h.driver == nil {
		return nil, fmt.Errorf("driver was failed to connected")
	}
	return h.driver, nil
}

// Connect is connected the connection of sqlite.
func (h *HelloSQLite) Connect() (err error) {
	h.driver, err = HelloSQLiteOpen(dialect.SQLite,
		h.File)
	if err != nil {
		log.Error().Err(err).Msg("HelloSQLiteOpen is failed to open")
		return err
	}
	pool := h.driver.DB()
	pool.SetMaxOpenConns(1)

	return nil
}

// Disconnect is disconnect the connection of sqlite.
func (h *HelloSQLite) Disconnect() error {
	return h.driver.Close()
}

// WithHelloSQLite option function to assign on adapters.
func WithHelloSQLite(driver Driver[*sqlEnt.Driver]) Option {
	return func(a *Adapter) {
		if err := driver.Connect(); err != nil {
			panic(err)
		}
		open, err := driver.Open()
		if err != nil {
			panic(err)
		}
		a.HelloSQLite = open
	}
}

