// Package adapters are the glue between components and external sources.
// # This manifest was generated by ymir. DO NOT EDIT.
package adapters

import (
	"fmt"

	"github.com/go-resty/resty/v2"
)

// PokemonResty is data of instances.
type PokemonResty struct {
	URL    string
	driver *resty.Client
}

// Open is open the connection of Pokemon.
func (p *PokemonResty) Open() (*resty.Client, error) {
	if p.driver == nil {
		return nil, fmt.Errorf("driver was failed to connected")
	}
	return p.driver, nil
}

// Connect is connected the connection of Pokemon.
func (p *PokemonResty) Connect() (err error) {
	p.driver = resty.New().SetBaseURL(p.URL)
	return nil
}

// Disconnect is disconnect the connection of Pokemon.
func (*PokemonResty) Disconnect() error {
	return nil
}

// WithPokemonResty option function to assign on adapters.
func WithPokemonResty(driver Driver[*resty.Client]) Option {
	return func(a *Adapter) {
		if err := driver.Connect(); err != nil {
			panic(err)
		}
		open, err := driver.Open()
		if err != nil {
			panic(err)
		}
		a.PokemonResty = open
	}
}
