// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kubuskotak/king/pkg/persist/crud/ent/hello"
)

// HelloCreate is the builder for creating a Hello entity.
type HelloCreate struct {
	config
	mutation *HelloMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (hc *HelloCreate) SetTitle(s string) *HelloCreate {
	hc.mutation.SetTitle(s)
	return hc
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (hc *HelloCreate) SetNillableTitle(s *string) *HelloCreate {
	if s != nil {
		hc.SetTitle(*s)
	}
	return hc
}

// SetBody sets the "body" field.
func (hc *HelloCreate) SetBody(s string) *HelloCreate {
	hc.mutation.SetBody(s)
	return hc
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (hc *HelloCreate) SetNillableBody(s *string) *HelloCreate {
	if s != nil {
		hc.SetBody(*s)
	}
	return hc
}

// SetDescription sets the "description" field.
func (hc *HelloCreate) SetDescription(s string) *HelloCreate {
	hc.mutation.SetDescription(s)
	return hc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (hc *HelloCreate) SetNillableDescription(s *string) *HelloCreate {
	if s != nil {
		hc.SetDescription(*s)
	}
	return hc
}

// SetSlug sets the "slug" field.
func (hc *HelloCreate) SetSlug(s string) *HelloCreate {
	hc.mutation.SetSlug(s)
	return hc
}

// SetUserID sets the "user_id" field.
func (hc *HelloCreate) SetUserID(i int) *HelloCreate {
	hc.mutation.SetUserID(i)
	return hc
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (hc *HelloCreate) SetNillableUserID(i *int) *HelloCreate {
	if i != nil {
		hc.SetUserID(*i)
	}
	return hc
}

// Mutation returns the HelloMutation object of the builder.
func (hc *HelloCreate) Mutation() *HelloMutation {
	return hc.mutation
}

// Save creates the Hello in the database.
func (hc *HelloCreate) Save(ctx context.Context) (*Hello, error) {
	hc.defaults()
	return withHooks(ctx, hc.sqlSave, hc.mutation, hc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (hc *HelloCreate) SaveX(ctx context.Context) *Hello {
	v, err := hc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (hc *HelloCreate) Exec(ctx context.Context) error {
	_, err := hc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hc *HelloCreate) ExecX(ctx context.Context) {
	if err := hc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (hc *HelloCreate) defaults() {
	if _, ok := hc.mutation.Title(); !ok {
		v := hello.DefaultTitle
		hc.mutation.SetTitle(v)
	}
	if _, ok := hc.mutation.Body(); !ok {
		v := hello.DefaultBody
		hc.mutation.SetBody(v)
	}
	if _, ok := hc.mutation.Description(); !ok {
		v := hello.DefaultDescription
		hc.mutation.SetDescription(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (hc *HelloCreate) check() error {
	if _, ok := hc.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Hello.title"`)}
	}
	if v, ok := hc.mutation.Title(); ok {
		if err := hello.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Hello.title": %w`, err)}
		}
	}
	if _, ok := hc.mutation.Body(); !ok {
		return &ValidationError{Name: "body", err: errors.New(`ent: missing required field "Hello.body"`)}
	}
	if v, ok := hc.mutation.Body(); ok {
		if err := hello.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "Hello.body": %w`, err)}
		}
	}
	if _, ok := hc.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Hello.description"`)}
	}
	if v, ok := hc.mutation.Description(); ok {
		if err := hello.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Hello.description": %w`, err)}
		}
	}
	if _, ok := hc.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "Hello.slug"`)}
	}
	if v, ok := hc.mutation.Slug(); ok {
		if err := hello.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Hello.slug": %w`, err)}
		}
	}
	return nil
}

func (hc *HelloCreate) sqlSave(ctx context.Context) (*Hello, error) {
	if err := hc.check(); err != nil {
		return nil, err
	}
	_node, _spec := hc.createSpec()
	if err := sqlgraph.CreateNode(ctx, hc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	hc.mutation.id = &_node.ID
	hc.mutation.done = true
	return _node, nil
}

func (hc *HelloCreate) createSpec() (*Hello, *sqlgraph.CreateSpec) {
	var (
		_node = &Hello{config: hc.config}
		_spec = sqlgraph.NewCreateSpec(hello.Table, sqlgraph.NewFieldSpec(hello.FieldID, field.TypeInt))
	)
	if value, ok := hc.mutation.Title(); ok {
		_spec.SetField(hello.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := hc.mutation.Body(); ok {
		_spec.SetField(hello.FieldBody, field.TypeString, value)
		_node.Body = value
	}
	if value, ok := hc.mutation.Description(); ok {
		_spec.SetField(hello.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := hc.mutation.Slug(); ok {
		_spec.SetField(hello.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := hc.mutation.UserID(); ok {
		_spec.SetField(hello.FieldUserID, field.TypeInt, value)
		_node.UserID = value
	}
	return _node, _spec
}

// HelloCreateBulk is the builder for creating many Hello entities in bulk.
type HelloCreateBulk struct {
	config
	builders []*HelloCreate
}

// Save creates the Hello entities in the database.
func (hcb *HelloCreateBulk) Save(ctx context.Context) ([]*Hello, error) {
	specs := make([]*sqlgraph.CreateSpec, len(hcb.builders))
	nodes := make([]*Hello, len(hcb.builders))
	mutators := make([]Mutator, len(hcb.builders))
	for i := range hcb.builders {
		func(i int, root context.Context) {
			builder := hcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HelloMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, hcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, hcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, hcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (hcb *HelloCreateBulk) SaveX(ctx context.Context) []*Hello {
	v, err := hcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (hcb *HelloCreateBulk) Exec(ctx context.Context) error {
	_, err := hcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hcb *HelloCreateBulk) ExecX(ctx context.Context) {
	if err := hcb.Exec(ctx); err != nil {
		panic(err)
	}
}
