// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kubuskotak/king/pkg/persist/crud/ent/hello"
	"github.com/kubuskotak/king/pkg/persist/crud/ent/predicate"
)

// HelloUpdate is the builder for updating Hello entities.
type HelloUpdate struct {
	config
	hooks    []Hook
	mutation *HelloMutation
}

// Where appends a list predicates to the HelloUpdate builder.
func (hu *HelloUpdate) Where(ps ...predicate.Hello) *HelloUpdate {
	hu.mutation.Where(ps...)
	return hu
}

// SetTitle sets the "title" field.
func (hu *HelloUpdate) SetTitle(s string) *HelloUpdate {
	hu.mutation.SetTitle(s)
	return hu
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (hu *HelloUpdate) SetNillableTitle(s *string) *HelloUpdate {
	if s != nil {
		hu.SetTitle(*s)
	}
	return hu
}

// SetBody sets the "body" field.
func (hu *HelloUpdate) SetBody(s string) *HelloUpdate {
	hu.mutation.SetBody(s)
	return hu
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (hu *HelloUpdate) SetNillableBody(s *string) *HelloUpdate {
	if s != nil {
		hu.SetBody(*s)
	}
	return hu
}

// SetDescription sets the "description" field.
func (hu *HelloUpdate) SetDescription(s string) *HelloUpdate {
	hu.mutation.SetDescription(s)
	return hu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (hu *HelloUpdate) SetNillableDescription(s *string) *HelloUpdate {
	if s != nil {
		hu.SetDescription(*s)
	}
	return hu
}

// SetSlug sets the "slug" field.
func (hu *HelloUpdate) SetSlug(s string) *HelloUpdate {
	hu.mutation.SetSlug(s)
	return hu
}

// SetUserID sets the "user_id" field.
func (hu *HelloUpdate) SetUserID(i int) *HelloUpdate {
	hu.mutation.ResetUserID()
	hu.mutation.SetUserID(i)
	return hu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (hu *HelloUpdate) SetNillableUserID(i *int) *HelloUpdate {
	if i != nil {
		hu.SetUserID(*i)
	}
	return hu
}

// AddUserID adds i to the "user_id" field.
func (hu *HelloUpdate) AddUserID(i int) *HelloUpdate {
	hu.mutation.AddUserID(i)
	return hu
}

// ClearUserID clears the value of the "user_id" field.
func (hu *HelloUpdate) ClearUserID() *HelloUpdate {
	hu.mutation.ClearUserID()
	return hu
}

// Mutation returns the HelloMutation object of the builder.
func (hu *HelloUpdate) Mutation() *HelloMutation {
	return hu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (hu *HelloUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, hu.sqlSave, hu.mutation, hu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (hu *HelloUpdate) SaveX(ctx context.Context) int {
	affected, err := hu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (hu *HelloUpdate) Exec(ctx context.Context) error {
	_, err := hu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hu *HelloUpdate) ExecX(ctx context.Context) {
	if err := hu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (hu *HelloUpdate) check() error {
	if v, ok := hu.mutation.Title(); ok {
		if err := hello.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Hello.title": %w`, err)}
		}
	}
	if v, ok := hu.mutation.Body(); ok {
		if err := hello.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "Hello.body": %w`, err)}
		}
	}
	if v, ok := hu.mutation.Description(); ok {
		if err := hello.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Hello.description": %w`, err)}
		}
	}
	if v, ok := hu.mutation.Slug(); ok {
		if err := hello.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Hello.slug": %w`, err)}
		}
	}
	return nil
}

func (hu *HelloUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := hu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(hello.Table, hello.Columns, sqlgraph.NewFieldSpec(hello.FieldID, field.TypeInt))
	if ps := hu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := hu.mutation.Title(); ok {
		_spec.SetField(hello.FieldTitle, field.TypeString, value)
	}
	if value, ok := hu.mutation.Body(); ok {
		_spec.SetField(hello.FieldBody, field.TypeString, value)
	}
	if value, ok := hu.mutation.Description(); ok {
		_spec.SetField(hello.FieldDescription, field.TypeString, value)
	}
	if value, ok := hu.mutation.Slug(); ok {
		_spec.SetField(hello.FieldSlug, field.TypeString, value)
	}
	if value, ok := hu.mutation.UserID(); ok {
		_spec.SetField(hello.FieldUserID, field.TypeInt, value)
	}
	if value, ok := hu.mutation.AddedUserID(); ok {
		_spec.AddField(hello.FieldUserID, field.TypeInt, value)
	}
	if hu.mutation.UserIDCleared() {
		_spec.ClearField(hello.FieldUserID, field.TypeInt)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, hu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{hello.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	hu.mutation.done = true
	return n, nil
}

// HelloUpdateOne is the builder for updating a single Hello entity.
type HelloUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *HelloMutation
}

// SetTitle sets the "title" field.
func (huo *HelloUpdateOne) SetTitle(s string) *HelloUpdateOne {
	huo.mutation.SetTitle(s)
	return huo
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (huo *HelloUpdateOne) SetNillableTitle(s *string) *HelloUpdateOne {
	if s != nil {
		huo.SetTitle(*s)
	}
	return huo
}

// SetBody sets the "body" field.
func (huo *HelloUpdateOne) SetBody(s string) *HelloUpdateOne {
	huo.mutation.SetBody(s)
	return huo
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (huo *HelloUpdateOne) SetNillableBody(s *string) *HelloUpdateOne {
	if s != nil {
		huo.SetBody(*s)
	}
	return huo
}

// SetDescription sets the "description" field.
func (huo *HelloUpdateOne) SetDescription(s string) *HelloUpdateOne {
	huo.mutation.SetDescription(s)
	return huo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (huo *HelloUpdateOne) SetNillableDescription(s *string) *HelloUpdateOne {
	if s != nil {
		huo.SetDescription(*s)
	}
	return huo
}

// SetSlug sets the "slug" field.
func (huo *HelloUpdateOne) SetSlug(s string) *HelloUpdateOne {
	huo.mutation.SetSlug(s)
	return huo
}

// SetUserID sets the "user_id" field.
func (huo *HelloUpdateOne) SetUserID(i int) *HelloUpdateOne {
	huo.mutation.ResetUserID()
	huo.mutation.SetUserID(i)
	return huo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (huo *HelloUpdateOne) SetNillableUserID(i *int) *HelloUpdateOne {
	if i != nil {
		huo.SetUserID(*i)
	}
	return huo
}

// AddUserID adds i to the "user_id" field.
func (huo *HelloUpdateOne) AddUserID(i int) *HelloUpdateOne {
	huo.mutation.AddUserID(i)
	return huo
}

// ClearUserID clears the value of the "user_id" field.
func (huo *HelloUpdateOne) ClearUserID() *HelloUpdateOne {
	huo.mutation.ClearUserID()
	return huo
}

// Mutation returns the HelloMutation object of the builder.
func (huo *HelloUpdateOne) Mutation() *HelloMutation {
	return huo.mutation
}

// Where appends a list predicates to the HelloUpdate builder.
func (huo *HelloUpdateOne) Where(ps ...predicate.Hello) *HelloUpdateOne {
	huo.mutation.Where(ps...)
	return huo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (huo *HelloUpdateOne) Select(field string, fields ...string) *HelloUpdateOne {
	huo.fields = append([]string{field}, fields...)
	return huo
}

// Save executes the query and returns the updated Hello entity.
func (huo *HelloUpdateOne) Save(ctx context.Context) (*Hello, error) {
	return withHooks(ctx, huo.sqlSave, huo.mutation, huo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (huo *HelloUpdateOne) SaveX(ctx context.Context) *Hello {
	node, err := huo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (huo *HelloUpdateOne) Exec(ctx context.Context) error {
	_, err := huo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (huo *HelloUpdateOne) ExecX(ctx context.Context) {
	if err := huo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (huo *HelloUpdateOne) check() error {
	if v, ok := huo.mutation.Title(); ok {
		if err := hello.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Hello.title": %w`, err)}
		}
	}
	if v, ok := huo.mutation.Body(); ok {
		if err := hello.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "Hello.body": %w`, err)}
		}
	}
	if v, ok := huo.mutation.Description(); ok {
		if err := hello.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Hello.description": %w`, err)}
		}
	}
	if v, ok := huo.mutation.Slug(); ok {
		if err := hello.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Hello.slug": %w`, err)}
		}
	}
	return nil
}

func (huo *HelloUpdateOne) sqlSave(ctx context.Context) (_node *Hello, err error) {
	if err := huo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(hello.Table, hello.Columns, sqlgraph.NewFieldSpec(hello.FieldID, field.TypeInt))
	id, ok := huo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Hello.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := huo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, hello.FieldID)
		for _, f := range fields {
			if !hello.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != hello.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := huo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := huo.mutation.Title(); ok {
		_spec.SetField(hello.FieldTitle, field.TypeString, value)
	}
	if value, ok := huo.mutation.Body(); ok {
		_spec.SetField(hello.FieldBody, field.TypeString, value)
	}
	if value, ok := huo.mutation.Description(); ok {
		_spec.SetField(hello.FieldDescription, field.TypeString, value)
	}
	if value, ok := huo.mutation.Slug(); ok {
		_spec.SetField(hello.FieldSlug, field.TypeString, value)
	}
	if value, ok := huo.mutation.UserID(); ok {
		_spec.SetField(hello.FieldUserID, field.TypeInt, value)
	}
	if value, ok := huo.mutation.AddedUserID(); ok {
		_spec.AddField(hello.FieldUserID, field.TypeInt, value)
	}
	if huo.mutation.UserIDCleared() {
		_spec.ClearField(hello.FieldUserID, field.TypeInt)
	}
	_node = &Hello{config: huo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, huo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{hello.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	huo.mutation.done = true
	return _node, nil
}
