// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/kubuskotak/king/pkg/persist/crud/ent/hello"
	"github.com/kubuskotak/king/pkg/persist/crud/ent/predicate"
	"github.com/kubuskotak/king/pkg/persist/crud/ent/ymir"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeHello = "Hello"
	TypeYmir  = "Ymir"
)

// HelloMutation represents an operation that mutates the Hello nodes in the graph.
type HelloMutation struct {
	config
	op            Op
	typ           string
	id            *int
	title         *string
	body          *string
	description   *string
	slug          *string
	user_id       *int
	adduser_id    *int
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Hello, error)
	predicates    []predicate.Hello
}

var _ ent.Mutation = (*HelloMutation)(nil)

// helloOption allows management of the mutation configuration using functional options.
type helloOption func(*HelloMutation)

// newHelloMutation creates new mutation for the Hello entity.
func newHelloMutation(c config, op Op, opts ...helloOption) *HelloMutation {
	m := &HelloMutation{
		config:        c,
		op:            op,
		typ:           TypeHello,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withHelloID sets the ID field of the mutation.
func withHelloID(id int) helloOption {
	return func(m *HelloMutation) {
		var (
			err   error
			once  sync.Once
			value *Hello
		)
		m.oldValue = func(ctx context.Context) (*Hello, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Hello.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withHello sets the old Hello of the mutation.
func withHello(node *Hello) helloOption {
	return func(m *HelloMutation) {
		m.oldValue = func(context.Context) (*Hello, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m HelloMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m HelloMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *HelloMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *HelloMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Hello.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetTitle sets the "title" field.
func (m *HelloMutation) SetTitle(s string) {
	m.title = &s
}

// Title returns the value of the "title" field in the mutation.
func (m *HelloMutation) Title() (r string, exists bool) {
	v := m.title
	if v == nil {
		return
	}
	return *v, true
}

// OldTitle returns the old "title" field's value of the Hello entity.
// If the Hello object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HelloMutation) OldTitle(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTitle is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTitle requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTitle: %w", err)
	}
	return oldValue.Title, nil
}

// ResetTitle resets all changes to the "title" field.
func (m *HelloMutation) ResetTitle() {
	m.title = nil
}

// SetBody sets the "body" field.
func (m *HelloMutation) SetBody(s string) {
	m.body = &s
}

// Body returns the value of the "body" field in the mutation.
func (m *HelloMutation) Body() (r string, exists bool) {
	v := m.body
	if v == nil {
		return
	}
	return *v, true
}

// OldBody returns the old "body" field's value of the Hello entity.
// If the Hello object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HelloMutation) OldBody(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldBody is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldBody requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldBody: %w", err)
	}
	return oldValue.Body, nil
}

// ResetBody resets all changes to the "body" field.
func (m *HelloMutation) ResetBody() {
	m.body = nil
}

// SetDescription sets the "description" field.
func (m *HelloMutation) SetDescription(s string) {
	m.description = &s
}

// Description returns the value of the "description" field in the mutation.
func (m *HelloMutation) Description() (r string, exists bool) {
	v := m.description
	if v == nil {
		return
	}
	return *v, true
}

// OldDescription returns the old "description" field's value of the Hello entity.
// If the Hello object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HelloMutation) OldDescription(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDescription is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDescription requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDescription: %w", err)
	}
	return oldValue.Description, nil
}

// ResetDescription resets all changes to the "description" field.
func (m *HelloMutation) ResetDescription() {
	m.description = nil
}

// SetSlug sets the "slug" field.
func (m *HelloMutation) SetSlug(s string) {
	m.slug = &s
}

// Slug returns the value of the "slug" field in the mutation.
func (m *HelloMutation) Slug() (r string, exists bool) {
	v := m.slug
	if v == nil {
		return
	}
	return *v, true
}

// OldSlug returns the old "slug" field's value of the Hello entity.
// If the Hello object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HelloMutation) OldSlug(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSlug is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSlug requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSlug: %w", err)
	}
	return oldValue.Slug, nil
}

// ResetSlug resets all changes to the "slug" field.
func (m *HelloMutation) ResetSlug() {
	m.slug = nil
}

// SetUserID sets the "user_id" field.
func (m *HelloMutation) SetUserID(i int) {
	m.user_id = &i
	m.adduser_id = nil
}

// UserID returns the value of the "user_id" field in the mutation.
func (m *HelloMutation) UserID() (r int, exists bool) {
	v := m.user_id
	if v == nil {
		return
	}
	return *v, true
}

// OldUserID returns the old "user_id" field's value of the Hello entity.
// If the Hello object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HelloMutation) OldUserID(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUserID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUserID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUserID: %w", err)
	}
	return oldValue.UserID, nil
}

// AddUserID adds i to the "user_id" field.
func (m *HelloMutation) AddUserID(i int) {
	if m.adduser_id != nil {
		*m.adduser_id += i
	} else {
		m.adduser_id = &i
	}
}

// AddedUserID returns the value that was added to the "user_id" field in this mutation.
func (m *HelloMutation) AddedUserID() (r int, exists bool) {
	v := m.adduser_id
	if v == nil {
		return
	}
	return *v, true
}

// ClearUserID clears the value of the "user_id" field.
func (m *HelloMutation) ClearUserID() {
	m.user_id = nil
	m.adduser_id = nil
	m.clearedFields[hello.FieldUserID] = struct{}{}
}

// UserIDCleared returns if the "user_id" field was cleared in this mutation.
func (m *HelloMutation) UserIDCleared() bool {
	_, ok := m.clearedFields[hello.FieldUserID]
	return ok
}

// ResetUserID resets all changes to the "user_id" field.
func (m *HelloMutation) ResetUserID() {
	m.user_id = nil
	m.adduser_id = nil
	delete(m.clearedFields, hello.FieldUserID)
}

// Where appends a list predicates to the HelloMutation builder.
func (m *HelloMutation) Where(ps ...predicate.Hello) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the HelloMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *HelloMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Hello, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *HelloMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *HelloMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Hello).
func (m *HelloMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *HelloMutation) Fields() []string {
	fields := make([]string, 0, 5)
	if m.title != nil {
		fields = append(fields, hello.FieldTitle)
	}
	if m.body != nil {
		fields = append(fields, hello.FieldBody)
	}
	if m.description != nil {
		fields = append(fields, hello.FieldDescription)
	}
	if m.slug != nil {
		fields = append(fields, hello.FieldSlug)
	}
	if m.user_id != nil {
		fields = append(fields, hello.FieldUserID)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *HelloMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case hello.FieldTitle:
		return m.Title()
	case hello.FieldBody:
		return m.Body()
	case hello.FieldDescription:
		return m.Description()
	case hello.FieldSlug:
		return m.Slug()
	case hello.FieldUserID:
		return m.UserID()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *HelloMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case hello.FieldTitle:
		return m.OldTitle(ctx)
	case hello.FieldBody:
		return m.OldBody(ctx)
	case hello.FieldDescription:
		return m.OldDescription(ctx)
	case hello.FieldSlug:
		return m.OldSlug(ctx)
	case hello.FieldUserID:
		return m.OldUserID(ctx)
	}
	return nil, fmt.Errorf("unknown Hello field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *HelloMutation) SetField(name string, value ent.Value) error {
	switch name {
	case hello.FieldTitle:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTitle(v)
		return nil
	case hello.FieldBody:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBody(v)
		return nil
	case hello.FieldDescription:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDescription(v)
		return nil
	case hello.FieldSlug:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSlug(v)
		return nil
	case hello.FieldUserID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUserID(v)
		return nil
	}
	return fmt.Errorf("unknown Hello field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *HelloMutation) AddedFields() []string {
	var fields []string
	if m.adduser_id != nil {
		fields = append(fields, hello.FieldUserID)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *HelloMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case hello.FieldUserID:
		return m.AddedUserID()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *HelloMutation) AddField(name string, value ent.Value) error {
	switch name {
	case hello.FieldUserID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddUserID(v)
		return nil
	}
	return fmt.Errorf("unknown Hello numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *HelloMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(hello.FieldUserID) {
		fields = append(fields, hello.FieldUserID)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *HelloMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *HelloMutation) ClearField(name string) error {
	switch name {
	case hello.FieldUserID:
		m.ClearUserID()
		return nil
	}
	return fmt.Errorf("unknown Hello nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *HelloMutation) ResetField(name string) error {
	switch name {
	case hello.FieldTitle:
		m.ResetTitle()
		return nil
	case hello.FieldBody:
		m.ResetBody()
		return nil
	case hello.FieldDescription:
		m.ResetDescription()
		return nil
	case hello.FieldSlug:
		m.ResetSlug()
		return nil
	case hello.FieldUserID:
		m.ResetUserID()
		return nil
	}
	return fmt.Errorf("unknown Hello field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *HelloMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *HelloMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *HelloMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *HelloMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *HelloMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *HelloMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *HelloMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Hello unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *HelloMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Hello edge %s", name)
}

// YmirMutation represents an operation that mutates the Ymir nodes in the graph.
type YmirMutation struct {
	config
	op            Op
	typ           string
	id            *int
	version       *string
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Ymir, error)
	predicates    []predicate.Ymir
}

var _ ent.Mutation = (*YmirMutation)(nil)

// ymirOption allows management of the mutation configuration using functional options.
type ymirOption func(*YmirMutation)

// newYmirMutation creates new mutation for the Ymir entity.
func newYmirMutation(c config, op Op, opts ...ymirOption) *YmirMutation {
	m := &YmirMutation{
		config:        c,
		op:            op,
		typ:           TypeYmir,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withYmirID sets the ID field of the mutation.
func withYmirID(id int) ymirOption {
	return func(m *YmirMutation) {
		var (
			err   error
			once  sync.Once
			value *Ymir
		)
		m.oldValue = func(ctx context.Context) (*Ymir, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Ymir.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withYmir sets the old Ymir of the mutation.
func withYmir(node *Ymir) ymirOption {
	return func(m *YmirMutation) {
		m.oldValue = func(context.Context) (*Ymir, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m YmirMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m YmirMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *YmirMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *YmirMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Ymir.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetVersion sets the "version" field.
func (m *YmirMutation) SetVersion(s string) {
	m.version = &s
}

// Version returns the value of the "version" field in the mutation.
func (m *YmirMutation) Version() (r string, exists bool) {
	v := m.version
	if v == nil {
		return
	}
	return *v, true
}

// OldVersion returns the old "version" field's value of the Ymir entity.
// If the Ymir object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *YmirMutation) OldVersion(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldVersion is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldVersion requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldVersion: %w", err)
	}
	return oldValue.Version, nil
}

// ResetVersion resets all changes to the "version" field.
func (m *YmirMutation) ResetVersion() {
	m.version = nil
}

// Where appends a list predicates to the YmirMutation builder.
func (m *YmirMutation) Where(ps ...predicate.Ymir) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the YmirMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *YmirMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Ymir, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *YmirMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *YmirMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Ymir).
func (m *YmirMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *YmirMutation) Fields() []string {
	fields := make([]string, 0, 1)
	if m.version != nil {
		fields = append(fields, ymir.FieldVersion)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *YmirMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case ymir.FieldVersion:
		return m.Version()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *YmirMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case ymir.FieldVersion:
		return m.OldVersion(ctx)
	}
	return nil, fmt.Errorf("unknown Ymir field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *YmirMutation) SetField(name string, value ent.Value) error {
	switch name {
	case ymir.FieldVersion:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetVersion(v)
		return nil
	}
	return fmt.Errorf("unknown Ymir field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *YmirMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *YmirMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *YmirMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Ymir numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *YmirMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *YmirMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *YmirMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Ymir nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *YmirMutation) ResetField(name string) error {
	switch name {
	case ymir.FieldVersion:
		m.ResetVersion()
		return nil
	}
	return fmt.Errorf("unknown Ymir field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *YmirMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *YmirMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *YmirMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *YmirMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *YmirMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *YmirMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *YmirMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Ymir unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *YmirMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Ymir edge %s", name)
}
