// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kubuskotak/king/pkg/persist/crud/ent/predicate"
	"github.com/kubuskotak/king/pkg/persist/crud/ent/ymir"
)

// YmirQuery is the builder for querying Ymir entities.
type YmirQuery struct {
	config
	ctx        *QueryContext
	order      []ymir.OrderOption
	inters     []Interceptor
	predicates []predicate.Ymir
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the YmirQuery builder.
func (yq *YmirQuery) Where(ps ...predicate.Ymir) *YmirQuery {
	yq.predicates = append(yq.predicates, ps...)
	return yq
}

// Limit the number of records to be returned by this query.
func (yq *YmirQuery) Limit(limit int) *YmirQuery {
	yq.ctx.Limit = &limit
	return yq
}

// Offset to start from.
func (yq *YmirQuery) Offset(offset int) *YmirQuery {
	yq.ctx.Offset = &offset
	return yq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (yq *YmirQuery) Unique(unique bool) *YmirQuery {
	yq.ctx.Unique = &unique
	return yq
}

// Order specifies how the records should be ordered.
func (yq *YmirQuery) Order(o ...ymir.OrderOption) *YmirQuery {
	yq.order = append(yq.order, o...)
	return yq
}

// First returns the first Ymir entity from the query.
// Returns a *NotFoundError when no Ymir was found.
func (yq *YmirQuery) First(ctx context.Context) (*Ymir, error) {
	nodes, err := yq.Limit(1).All(setContextOp(ctx, yq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{ymir.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (yq *YmirQuery) FirstX(ctx context.Context) *Ymir {
	node, err := yq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Ymir ID from the query.
// Returns a *NotFoundError when no Ymir ID was found.
func (yq *YmirQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = yq.Limit(1).IDs(setContextOp(ctx, yq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{ymir.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (yq *YmirQuery) FirstIDX(ctx context.Context) int {
	id, err := yq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Ymir entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Ymir entity is found.
// Returns a *NotFoundError when no Ymir entities are found.
func (yq *YmirQuery) Only(ctx context.Context) (*Ymir, error) {
	nodes, err := yq.Limit(2).All(setContextOp(ctx, yq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{ymir.Label}
	default:
		return nil, &NotSingularError{ymir.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (yq *YmirQuery) OnlyX(ctx context.Context) *Ymir {
	node, err := yq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Ymir ID in the query.
// Returns a *NotSingularError when more than one Ymir ID is found.
// Returns a *NotFoundError when no entities are found.
func (yq *YmirQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = yq.Limit(2).IDs(setContextOp(ctx, yq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{ymir.Label}
	default:
		err = &NotSingularError{ymir.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (yq *YmirQuery) OnlyIDX(ctx context.Context) int {
	id, err := yq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Ymirs.
func (yq *YmirQuery) All(ctx context.Context) ([]*Ymir, error) {
	ctx = setContextOp(ctx, yq.ctx, "All")
	if err := yq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Ymir, *YmirQuery]()
	return withInterceptors[[]*Ymir](ctx, yq, qr, yq.inters)
}

// AllX is like All, but panics if an error occurs.
func (yq *YmirQuery) AllX(ctx context.Context) []*Ymir {
	nodes, err := yq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Ymir IDs.
func (yq *YmirQuery) IDs(ctx context.Context) (ids []int, err error) {
	if yq.ctx.Unique == nil && yq.path != nil {
		yq.Unique(true)
	}
	ctx = setContextOp(ctx, yq.ctx, "IDs")
	if err = yq.Select(ymir.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (yq *YmirQuery) IDsX(ctx context.Context) []int {
	ids, err := yq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (yq *YmirQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, yq.ctx, "Count")
	if err := yq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, yq, querierCount[*YmirQuery](), yq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (yq *YmirQuery) CountX(ctx context.Context) int {
	count, err := yq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (yq *YmirQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, yq.ctx, "Exist")
	switch _, err := yq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (yq *YmirQuery) ExistX(ctx context.Context) bool {
	exist, err := yq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the YmirQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (yq *YmirQuery) Clone() *YmirQuery {
	if yq == nil {
		return nil
	}
	return &YmirQuery{
		config:     yq.config,
		ctx:        yq.ctx.Clone(),
		order:      append([]ymir.OrderOption{}, yq.order...),
		inters:     append([]Interceptor{}, yq.inters...),
		predicates: append([]predicate.Ymir{}, yq.predicates...),
		// clone intermediate query.
		sql:  yq.sql.Clone(),
		path: yq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Version string `json:"version,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Ymir.Query().
//		GroupBy(ymir.FieldVersion).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (yq *YmirQuery) GroupBy(field string, fields ...string) *YmirGroupBy {
	yq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &YmirGroupBy{build: yq}
	grbuild.flds = &yq.ctx.Fields
	grbuild.label = ymir.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Version string `json:"version,omitempty"`
//	}
//
//	client.Ymir.Query().
//		Select(ymir.FieldVersion).
//		Scan(ctx, &v)
func (yq *YmirQuery) Select(fields ...string) *YmirSelect {
	yq.ctx.Fields = append(yq.ctx.Fields, fields...)
	sbuild := &YmirSelect{YmirQuery: yq}
	sbuild.label = ymir.Label
	sbuild.flds, sbuild.scan = &yq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a YmirSelect configured with the given aggregations.
func (yq *YmirQuery) Aggregate(fns ...AggregateFunc) *YmirSelect {
	return yq.Select().Aggregate(fns...)
}

func (yq *YmirQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range yq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, yq); err != nil {
				return err
			}
		}
	}
	for _, f := range yq.ctx.Fields {
		if !ymir.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if yq.path != nil {
		prev, err := yq.path(ctx)
		if err != nil {
			return err
		}
		yq.sql = prev
	}
	return nil
}

func (yq *YmirQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Ymir, error) {
	var (
		nodes = []*Ymir{}
		_spec = yq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Ymir).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Ymir{config: yq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, yq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (yq *YmirQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := yq.querySpec()
	_spec.Node.Columns = yq.ctx.Fields
	if len(yq.ctx.Fields) > 0 {
		_spec.Unique = yq.ctx.Unique != nil && *yq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, yq.driver, _spec)
}

func (yq *YmirQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(ymir.Table, ymir.Columns, sqlgraph.NewFieldSpec(ymir.FieldID, field.TypeInt))
	_spec.From = yq.sql
	if unique := yq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if yq.path != nil {
		_spec.Unique = true
	}
	if fields := yq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ymir.FieldID)
		for i := range fields {
			if fields[i] != ymir.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := yq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := yq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := yq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := yq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (yq *YmirQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(yq.driver.Dialect())
	t1 := builder.Table(ymir.Table)
	columns := yq.ctx.Fields
	if len(columns) == 0 {
		columns = ymir.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if yq.sql != nil {
		selector = yq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if yq.ctx.Unique != nil && *yq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range yq.predicates {
		p(selector)
	}
	for _, p := range yq.order {
		p(selector)
	}
	if offset := yq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := yq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// YmirGroupBy is the group-by builder for Ymir entities.
type YmirGroupBy struct {
	selector
	build *YmirQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ygb *YmirGroupBy) Aggregate(fns ...AggregateFunc) *YmirGroupBy {
	ygb.fns = append(ygb.fns, fns...)
	return ygb
}

// Scan applies the selector query and scans the result into the given value.
func (ygb *YmirGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ygb.build.ctx, "GroupBy")
	if err := ygb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*YmirQuery, *YmirGroupBy](ctx, ygb.build, ygb, ygb.build.inters, v)
}

func (ygb *YmirGroupBy) sqlScan(ctx context.Context, root *YmirQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ygb.fns))
	for _, fn := range ygb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ygb.flds)+len(ygb.fns))
		for _, f := range *ygb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ygb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ygb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// YmirSelect is the builder for selecting fields of Ymir entities.
type YmirSelect struct {
	*YmirQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ys *YmirSelect) Aggregate(fns ...AggregateFunc) *YmirSelect {
	ys.fns = append(ys.fns, fns...)
	return ys
}

// Scan applies the selector query and scans the result into the given value.
func (ys *YmirSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ys.ctx, "Select")
	if err := ys.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*YmirQuery, *YmirSelect](ctx, ys.YmirQuery, ys, ys.inters, v)
}

func (ys *YmirSelect) sqlScan(ctx context.Context, root *YmirQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ys.fns))
	for _, fn := range ys.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ys.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ys.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
