// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Hello is the predicate function for hello builders.
type Hello func(*sql.Selector)

// Ymir is the predicate function for ymir builders.
type Ymir func(*sql.Selector)
